import { chromium } from 'playwright';
const S = process.argv[2]; const B = 'http://localhost:3002';
const res = []; const check = (n, ok, x = '') => res.push((ok ? 'PASS' : 'FAIL') + '  ' + n + (x ? '  (' + x + ')' : ''));
const b = await chromium.launch();
// Start from the built-in funnel: taking down any test publication also refreshes the cached page.
const adm = await b.newContext({ storageState: S + '/auth.json' }); await adm.request.delete(B + '/api/admin/publish?slug=masquerade'); await adm.close();
const ctx = await b.newContext({ timezoneId: 'America/Detroit', viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 2 });
const p = await ctx.newPage(); const errs = []; p.on('pageerror', e => errs.push(e.message));
const leads = []; await p.route('**/api/leads', async (r) => { leads.push(JSON.parse(r.request().postData())); await r.fulfill({ status: 201, contentType: 'application/json', body: '{"ok":true}' }); });
await p.goto(B + '/f/masquerade'); await p.waitForTimeout(1200);
check('no concept banner', await p.getByText(/Concept preview/).count() === 0);
check('title', await p.getByRole('heading', { name: 'Masquerade on the Runway' }).isVisible());
check('date in Detroit time', await p.getByText('Saturday · 8 PM').isVisible());
const href = await p.getByRole('link', { name: /Get tickets/ }).first().getAttribute('href');
check('Eventbrite link with tracking', href.startsWith('https://www.eventbrite.com/e/masquerade-on-the-runway-tickets-1998119183265?aff=reels_'), href);
check('flyer behind the title', await p.locator('img[src*="masquerade"][src*="flyer"]').count() > 0);
await p.getByRole('button', { name: /Sneak peek inside/ }).click(); await p.waitForTimeout(1000);
check('first reel: masks on', await p.getByText('Masks on. Secrets revealed.').first().isVisible());
await p.getByRole('button', { name: 'Updates' }).first().click(); await p.waitForTimeout(500);
const sheet = p.locator('form').last();
check('updates sheet', await p.getByRole('heading', { name: 'Get event updates' }).isVisible());
await sheet.getByLabel('First name').fill('Ava'); await sheet.getByLabel('Mobile number').fill('(313) 555-0123');
await sheet.getByRole('checkbox').first().check().catch(() => {});
await sheet.getByRole('button', { name: 'Text me updates' }).click(); await p.waitForTimeout(800);
check('lead actually sent', leads.length === 1 && leads[0].funnelId === 'masquerade-v1', JSON.stringify(leads).slice(0, 200));
await ctx.close(); const ctx2 = await b.newContext({ storageState: S + '/auth.json' }); const p2 = await ctx2.newPage(); p2.on('pageerror', e => errs.push(e.message)); await p2.goto(B + '/admin'); await p2.waitForTimeout(800);
check('admin lists Big Love, not Golden Hour', (await p2.locator('#admin-business option').allTextContents()).join('|').includes('Big Love') && !(await p2.locator('#admin-business option').allTextContents()).join('|').includes('Golden Hour'));
check('no page errors', errs.length === 0, errs.join(' | '));
console.log(res.join('\n')); console.log(res.filter(r => r.startsWith('FAIL')).length ? 'SOME FAILED' : 'ALL PASS');
await b.close();
