// Private DM demos ("Prepared for ..."), generated by scripts/new-demo.mjs.
// This file is rewritten by that script; don't edit it by hand.

import type { Funnel } from "@/data/funnel-types";


export const demoFunnels: Funnel[] = [];
