#!/usr/bin/env node
// Builds a private "Prepared for ..." demo funnel for one prospect, for a DM
// pitch: their name, colors, ticket links and their own clips.
//
//   node scripts/new-demo.mjs prospect.json        create a demo
//   node scripts/new-demo.mjs --remove <slug>      delete a demo and its media
//   node scripts/new-demo.mjs --list               list demos
//
// See scripts/demo-template/example.json for the input. Clips are prepared
// with scripts/prepare-reel.sh (needs ffmpeg) into public/demos/<slug>/.
// The link gets a random suffix so it can't be guessed, and every demo is
// labeled "Prepared for ...", never indexed, and sends nothing. Delete it
// with --remove if the prospect says no.

import { execFileSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { basename, dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const demosDir = join(root, "src/data/demos");
const mediaRoot = join(root, "public/demos");

const fail = (message) => {
  console.error(`new-demo: ${message}`);
  process.exit(1);
};

// ---------------------------------------------------------------------------
// The demos index (src/data/demos/index.ts) lists every demo file.

function writeIndex() {
  const files = readdirSync(demosDir)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .sort();
  const names = files.map((f) => ({
    file: f.replace(/\.ts$/, ""),
    id: "demo_" + f.replace(/\.ts$/, "").replace(/[^a-zA-Z0-9]/g, "_"),
  }));
  writeFileSync(
    join(demosDir, "index.ts"),
    `// Private DM demos ("Prepared for ..."), generated by scripts/new-demo.mjs.
// This file is rewritten by that script; don't edit it by hand.

import type { Funnel } from "@/data/funnel-types";
${names.map((n) => `import { funnel as ${n.id} } from "@/data/demos/${n.file}";`).join("\n")}

export const demoFunnels: Funnel[] = [${names.map((n) => n.id).join(", ")}];
`
  );
}

const args = process.argv.slice(2);
if (args[0] === "--list") {
  const files = readdirSync(demosDir).filter((f) => f.endsWith(".ts") && f !== "index.ts");
  console.log(files.length ? files.map((f) => `/f/${f.replace(/\.ts$/, "")}`).join("\n") : "No demos yet.");
  process.exit(0);
}
if (args[0] === "--remove") {
  const slug = args[1];
  if (!slug || !/^[a-z0-9-]+$/.test(slug)) fail("usage: --remove <slug>");
  const file = join(demosDir, `${slug}.ts`);
  if (!existsSync(file)) fail(`no demo called ${slug}`);
  rmSync(file);
  rmSync(join(mediaRoot, slug), { recursive: true, force: true });
  writeIndex();
  console.log(`Removed /f/${slug}. Commit and deploy to take it offline.`);
  process.exit(0);
}
if (!args[0]) fail("usage: node scripts/new-demo.mjs prospect.json (see scripts/demo-template/example.json)");

// ---------------------------------------------------------------------------
// Read and check the prospect file.

const spec = JSON.parse(readFileSync(resolve(args[0]), "utf8"));
for (const key of ["name", "preparedFor", "colors", "events", "reels"]) {
  if (!spec[key]) fail(`missing "${key}"`);
}
if (!spec.reels.length) fail("add at least one reel");
const eventIds = new Set(spec.events.map((e) => e.id));
for (const e of spec.events) {
  if (!e.id || !e.name || !e.startsAt || !e.ticketUrl) fail(`event needs id, name, startsAt and ticketUrl: ${JSON.stringify(e)}`);
  if (Number.isNaN(Date.parse(e.startsAt))) fail(`bad startsAt for ${e.id}: ${e.startsAt}`);
  if (!/^https:\/\//.test(e.ticketUrl)) fail(`ticketUrl must start with https:// (${e.id})`);
}
const hex = /^#[0-9a-fA-F]{6}$/;
for (const c of ["background", "accent", "highlight"]) {
  if (!hex.test(spec.colors[c] ?? "")) fail(`colors.${c} must be a #rrggbb color`);
}

// White text sits on the accent color, so it needs 4.5:1 contrast.
function luminance(h) {
  const c = [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16) / 255).map((x) => (x <= 0.03928 ? x / 12.92 : ((x + 0.055) / 1.055) ** 2.4));
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
}
const contrast = (a, b) => {
  const [x, y] = [luminance(a), luminance(b)].sort((p, q) => q - p);
  return (x + 0.05) / (y + 0.05);
};
if (contrast("#ffffff", spec.colors.accent) < 4.5) {
  fail(`white text on accent ${spec.colors.accent} is too faint (${contrast("#ffffff", spec.colors.accent).toFixed(2)}:1, needs 4.5). Pick a darker accent.`);
}
// A step from the background toward the accent, for gradients.
const mix = (a, b, t) =>
  "#" + [1, 3, 5].map((i) => Math.round(parseInt(a.slice(i, i + 2), 16) * (1 - t) + parseInt(b.slice(i, i + 2), 16) * t).toString(16).padStart(2, "0")).join("");

const slugify = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 32);
const slug = `${slugify(spec.name)}-${randomBytes(3).toString("hex")}`;
const mediaDir = join(mediaRoot, slug);
mkdirSync(mediaDir, { recursive: true });

// ---------------------------------------------------------------------------
// Media: prepare clips, copy photos, read YouTube links.

const youtubeId = (url) => {
  const m = String(url).match(/(?:youtu\.be\/|[?&]v=|\/shorts\/|\/embed\/|\/live\/)([A-Za-z0-9_-]{11})/);
  return m ? m[1] : null;
};
const expand = (p) => resolve(p.replace(/^~(?=\/)/, homedir()));

const reels = spec.reels.map((r, i) => {
  if (!r.title || !r.topic) fail(`reel ${i + 1} needs a title and a topic`);
  if (r.event && !eventIds.has(r.event)) fail(`reel ${i + 1} points at unknown event "${r.event}"`);
  const id = `r${i + 1}-${slugify(r.title).slice(0, 24)}`;
  let media;
  if (r.clip) {
    const input = expand(r.clip);
    if (!existsSync(input)) fail(`clip not found: ${input}`);
    const out = join(mediaDir, String(i + 1));
    console.log(`Preparing ${basename(input)}...`);
    execFileSync(join(root, "scripts/prepare-reel.sh"), [input, out, String(r.start ?? 0), String(r.length ?? 30)], { stdio: "inherit" });
    media = { kind: "video", src: `/demos/${slug}/${i + 1}.mp4`, poster: `/demos/${slug}/${i + 1}.jpg` };
  } else if (r.youtube) {
    const yt = youtubeId(r.youtube);
    if (!yt) fail(`reel ${i + 1}: not a YouTube link: ${r.youtube}`);
    media = { kind: "youtube", id: yt };
  } else if (r.photo) {
    const input = expand(r.photo);
    if (!existsSync(input)) fail(`photo not found: ${input}`);
    const name = `${i + 1}${extname(input).toLowerCase()}`;
    copyFileSync(input, join(mediaDir, name));
    media = { kind: "image", src: `/demos/${slug}/${name}` };
  }
  return {
    id,
    practiceArea: r.topic,
    title: r.title,
    summary: r.summary ?? "",
    ...(r.badge ? { badge: r.badge } : {}),
    ...(r.event ? { eventId: r.event } : {}),
    ...(r.emphasis ? { emphasis: r.emphasis } : {}),
    ...(media ? { media } : {}),
  };
});

// Each reel leads to the next; the first reel for each event (and each
// recap) is a starting point.
const links = Object.fromEntries(
  reels.map((r, i) => [r.id, { completed: reels[i + 1]?.id ?? null, skipped: reels[i + 1]?.id ?? null }])
);
const entryReelIds = [...new Set(reels.filter((r) => r.eventId).map((r) => reels.find((x) => x.eventId === r.eventId).id))];
if (!entryReelIds.length) entryReelIds.push(reels[0].id);
const services = [...new Set(reels.map((r) => r.practiceArea))];

const name = spec.name;
const funnel = {
  id: `demo-${slug}`,
  slug,
  sample: {
    notice: `Private preview prepared for ${spec.preparedFor}. Not live: nothing you enter is sent.`,
    preparedFor: spec.preparedFor,
  },
  primaryCta: "tickets",
  ticketing: { provider: spec.ticketing ?? "other" },
  events: spec.events.map((e) => ({ ...e })),
  reels,
  cover: {
    heading: spec.coverHeading ?? "Which night?",
    intro: spec.coverIntro ?? "Tap a date to watch the vibe, then grab tickets in one tap.",
    entryLabels: {},
    // The opening scene plays the first clip behind this title.
    hero: {
      title: spec.heroTitle ?? name,
      ...(spec.heroTagline ?? spec.byline?.[0] ? { tagline: spec.heroTagline ?? spec.byline[0] } : {}),
      watchLabel: "Watch the vibe",
    },
  },
  entryReelIds,
  links,
};

const brand = {
  name,
  logo: spec.logo ?? { kind: "wordmark", text: name, ...(spec.tagline ? { tagline: spec.tagline } : {}) },
  ...(spec.handle ? { handle: spec.handle } : {}),
  ...(spec.byline ? { byline: spec.byline } : {}),
  theme: {
    "--deep-navy": spec.colors.background,
    "--royal-blue": mix(spec.colors.background, spec.colors.accent, 0.25),
    "--teal-accent": spec.colors.accent,
    "--sky-accent": spec.colors.highlight,
    "--soft-gray": "#F5F5F4",
  },
  services,
  smsConsent: `I agree that ${name} may text me at this number about presales and upcoming events. Up to 4 messages a month. Msg & data rates may apply. Reply STOP to opt out.`,
  seriesLabel: name,
  disclaimer: spec.disclaimer ?? "Lineups and set times can change.",
  footer: spec.footer ?? spec.disclaimer ?? "Tickets are sold by our ticketing partner.",
};

const q = (v) => JSON.stringify(v, null, 2);
// An object's properties without its braces, indented, to write inline (so
// TypeScript checks every value against the Funnel type).
const props = (v, indent) =>
  q(v).slice(1, -1).trim().split("\n").map((line) => indent + line.replace(/^  /, "")).join("\n");
writeFileSync(
  join(demosDir, `${slug}.ts`),
  `// Private demo prepared for ${spec.preparedFor}, generated by scripts/new-demo.mjs.
// Remove with: node scripts/new-demo.mjs --remove ${slug}

import type { Funnel } from "@/data/funnel-types";

export const funnel: Funnel = {
${props(funnel, "  ")},
  brand: {
${props(brand, "    ")},
    copy: {
      ticketsPrimary: "Get tickets",
      textLaterButton: "Presale",
      bookPrimary: "Get tickets",
      callBack: "Request a call back",
      callNow: "Call",
      coverCallPrompt: "Already know you're coming?",
      coverCall: "Get tickets for the next one",
      book: { heading: "Get tickets", intro: "", submit: "Continue" },
      bookDone: (name) => \`Thanks, \${name}.\`,
      textLater: {
        heading: "Get presale access",
        intro: "We'll text you before tickets go on sale, so you're first in line.",
        submit: "Text me the presale",
      },
      textLaterDone: (name, number) => \`You're on the list, \${name}. Presale links go to \${number}.\`,
      formFinePrint: "No spam: presales and big announcements only.",
      endHeading: ${q(spec.endHeading ?? "See you there?")},
      endBody: ${q(spec.endBody ?? "Tickets go fast. Grab yours, or get first access to the next presale.")},
      shareButton: "Send to the group chat",
      shareText: ${q(spec.shareText ?? `${name}: watch the vibe, then grab tickets.`)},
    },
  },
};
`
);
writeIndex();

console.log(`
Demo ready: /f/${slug}
  Prepared for ${spec.preparedFor}. Labeled, not indexed, sends nothing.
  Next: commit and deploy, then open https://<your-domain>/f/${slug} on your phone before you DM it.
  Remove: node scripts/new-demo.mjs --remove ${slug}
`);
